{\rtf1\ansi\ansicpg1252\cocoartf2511
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\margl1440\margr1440\vieww18220\viewh11040\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 v\
Traceback (most recent call last):\
  File "/Users/matthewpraino/.devops/lib/python3.8/site-packages/flask/app.py", line 2463, in __call__\
    return self.wsgi_app(environ, start_response)\
  File "/Users/matthewpraino/.devops/lib/python3.8/site-packages/flask/app.py", line 2449, in wsgi_app\
    response = self.handle_exception(e)\
  File "/Users/matthewpraino/.devops/lib/python3.8/site-packages/flask/app.py", line 1866, in handle_exception\
    reraise(exc_type, exc_value, tb)\
  File "/Users/matthewpraino/.devops/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise\
    raise value\
  File "/Users/matthewpraino/.devops/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app\
    response = self.full_dispatch_request()\
  File "/Users/matthewpraino/.devops/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request\
    rv = self.handle_user_exception(e)\
  File "/Users/matthewpraino/.devops/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception\
    reraise(exc_type, exc_value, tb)\
  File "/Users/matthewpraino/.devops/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise\
    raise value\
  File "/Users/matthewpraino/.devops/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request\
    rv = self.dispatch_request()\
  File "/Users/matthewpraino/.devops/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request\
    return self.view_functions[rule.endpoint](**req.view_args)\
  File "/Users/matthewpraino/temp/local_environment/DevOps_Microservices/project-ml-microservice-kubernetes/app.py", line 64, in predict\
    prediction = list(clf.predict(scaled_payload))\
  File "/Users/matthewpraino/.devops/lib/python3.8/site-packages/sklearn/ensemble/_gb.py", line 2569, in predict\
    return self._raw_predict(X).ravel()\
  File "/Users/matthewpraino/.devops/lib/python3.8/site-packages/sklearn/ensemble/_gb.py", line 1655, in _raw_predict\
    raw_predictions = self._raw_predict_init(X)\
  File "/Users/matthewpraino/.devops/lib/python3.8/site-packages/sklearn/ensemble/_gb.py", line 1649, in _raw_predict_init\
    raw_predictions = self.loss_.get_init_raw_predictions(\
AttributeError: 'LeastSquaresError' object has no attribute 'get_init_raw_predictions'}